server:
  port: ${PORT:31001}
  servlet:
    context-path: /cms
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://docker-base:27017
      database: xc_cms
  rabbitmq:
    host: docker-base
    port: 5672
    username: guest
    password: guest
    virtualHost: /
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0