server:
  port: ${port:40100}
spring:
  application:
    name: xc-service-search
  elasticsearch:
    uris: docker-base:9200

xuecheng:
  course:
    index: xc_course_2
    type: course2
    source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_time,start_time,end_time
  media:
    index: xc_course_media
    type: doc
    source_field: courseid,media_id,media_url,teachplan_id,media_fileoriginalname