server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri: mongodb://docker-base:27017
      database: xc_media
  #rabbitmq配置
  rabbitmq:
    host: docker-base
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: E:/develop/video/
  ffmpeg-path: E:/ffmpeg-20191126-59d264b-win64-static/bin/ffmpeg.exe