server:
  port: 30000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://docker-base:27017
      database: xc_cms
  rabbitmq:
    host: docker-base
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    routingKey: 5de5db869b8ebb432cede9c1  #此routingKey为门户站点ID