server:
  port: 50101
spring:
  application:
    name: xc‐govern-center

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:50101/eureka
  server:
    enable-self-preservation: false # 是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000   #服务注册表清理时间