server:
  port: 31200
  servlet:
    context-path: /course
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://docker-base:3306/xc_course?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  data:
    mongodb:
      uri: mongodb://docker-base:27017
      database: xc_cms
pagehelper:
  helper-dialect: mysql

course-publish:
  siteId: 5de5db869b8ebb432cede9c1
  templateId: 5deb5e4a9b8ebb42ccffce7d
  previewUrl: http://www.xuecheng.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31200/course/courseview/