server:
  port: 31400
spring:
  application:
    name: xc-service-manage-media
  data:
    mongodb:
      uri: mongodb://docker-base:27017
      database: xc_media
xc-service-manage-media:
  upload-location: E:/develop/video/
  mq:
    routingkey-media-video: routingkey_media_video