server:
  port: 50201

spring:
  application:
    name: xc-govern-gateway
  main:
    web-application-type: reactive
  redis:
    host: ${REDIS_HOST:docker-base}
    port: ${REDIS_PORT:6379}
    timeout: 5000

  cloud:
    gateway:
      routes:
        - id: xc-service-manage-course
          uri: lb://xc-service-manage-course
          predicates:
            - Path=/api/course/**
          filters:
            - StripPrefix=1
        - id: xc-service-learning
          uri: lb://xc-service-learning
          predicates:
            - Path=/api/learning/**
          filters:
            - StripPrefix=1
        - id: xc-service-manage-cms
          uri: lb://xc-service-manage-cms
          predicates:
            - Path=/api/cms/**,/api/sys/**
          filters:
            - StripPrefix=1
        - id: xc-service-ucenter
          uri: lb://xc-service-ucenter
          predicates:
            - Path=/api/ucenter/**
          filters:
            - StripPrefix=1
        - id: xc-service-ucenter-auth
          uri: lb://xc-service-ucenter-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: xc-service-order
          uri: lb://xc-service-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1


