server:
  port: 50201
  servlet:
    context-path: /api
spring:
  application:
    name: xc-govern-gateway
  redis:
    host: ${REDIS_HOST:docker-base}
    port: ${REDIS_PORT:6379}
    timeout: 5000

  cloud:
    gateway:
      routes:
        - id: xc-service-manage-course
          uri: lb://xc-service-manage-course
          predicates:
            - path: /course/**
        - id: xc-service-learning
          uri: lb://xc-service-learning
          predicates:
            - path: /learning/**
        - id: xc-service-manage-cms
          uri: lb://xc-service-manage-cms
          predicates:
            - path: /cms/**,/sys/**
        - id: xc-service-ucenter
          uri: lb://xc-service-ucenter
          predicates:
            - path: /ucenter/**

        - id: xc-service-order
          uri: lb://xc-service-order
          predicates:
            - path: /order/**